# Generated by Django 2.1.8 on 2019-07-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_data', models.CharField(blank=True, max_length=100, null=True)),
                ('col_order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('cat', models.CharField(blank=True, max_length=100, null=True)),
                ('lev3', models.CharField(blank=True, max_length=100, null=True)),
                ('lev4', models.CharField(blank=True, max_length=100, null=True)),
                ('col_A', models.CharField(blank=True, max_length=100, null=True)),
                ('col_B', models.CharField(blank=True, max_length=100, null=True)),
                ('col_C', models.CharField(blank=True, max_length=100, null=True)),
                ('col_D', models.CharField(blank=True, max_length=100, null=True)),
                ('col_E', models.CharField(blank=True, max_length=100, null=True)),
                ('col_F', models.CharField(blank=True, max_length=100, null=True)),
                ('col_G', models.CharField(blank=True, max_length=100, null=True)),
                ('col_H', models.CharField(blank=True, max_length=100, null=True)),
                ('col_I', models.CharField(blank=True, max_length=100, null=True)),
                ('col_J', models.CharField(blank=True, max_length=100, null=True)),
                ('col_K', models.CharField(blank=True, max_length=100, null=True)),
                ('col_L', models.CharField(blank=True, max_length=100, null=True)),
                ('col_M', models.CharField(blank=True, max_length=100, null=True)),
                ('col_N', models.CharField(blank=True, max_length=100, null=True)),
                ('col_O', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
