# Generated by Django 2.1.8 on 2019-07-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='col_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
