# Generated by Django 2.1.8 on 2019-07-25 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_column_col_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='col_order',
        ),
    ]
