# Generated by Django 2.1.8 on 2019-07-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_auto_20190726_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
