# Generated by Django 2.1.8 on 2019-07-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0005_invest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='col_width',
            field=models.FloatField(blank=True, default=1.0),
            preserve_default=False,
        ),
    ]
