# Generated by Django 2.1.8 on 2019-07-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0006_column_col_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='col_width',
        ),
        migrations.AddField(
            model_name='column',
            name='col_show',
            field=models.NullBooleanField(),
        ),
    ]
