# Generated by Django 2.1.8 on 2019-07-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0010_remove_invest_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.EmailField(max_length=254)),
                ('subject_text', models.CharField(max_length=500)),
                ('body_text', models.TextField(blank=True)),
            ],
        ),
    ]
