# Generated by Django 2.1.8 on 2019-07-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190719_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='col_id',
        ),
        migrations.AddField(
            model_name='column',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
