# Generated by Django 2.1.8 on 2019-07-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190719_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='col_id',
            new_name='column',
        ),
    ]
